on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_STATIC_WEBAPP_NAME: ohyeahmrpostman2    # set this to your static web app name
  NODE_VERSION: '20.x'                          # set this to the node version to use

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'

    - name: npm install, build, and test
      run: |
        npm install
        npm run build --if-present
        npm run test --if-present
    
    - name: Upload artifact for deployment job
      uses: actions/upload-artifact@v3
      with:
        name: node-app
        path: ./

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: node-app

    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        app_location: "/"  # Location of your application source code
        output_location: "build"  # Location of the build output directory (can be 'dist' or 'build' depending on your project)
        api_location: ""  # Location of your Azure Functions API (if any)
        azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEBAPP_TOKEN }}
