name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # or any branch you want to trigger the deployment on
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Build and Deploy to Azure Static Web App
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Build and Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          app_location: "/"              # Path to your application, adjust if it's in a subfolder
          api_location: "api"            # Path to your API, optional - remove if you don’t have an API
          output_location: "build"       # Output directory after your app is built
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}  # Token for deployment
