name: Build and deploy ASP app to Azure Web App - texasPost

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'
          
      - name: List repository files
        run: Get-ChildItem -Path ${{ github.workspace }} -Recurse
        shell: pwsh



      - name: Restore NuGet packages
        run: dotnet restore backend/PostOfficeDB.csproj

      - name: Publish Web App
        run: dotnet publish ./PostOfficeWebApp/PostOfficeWebApp.csproj --configuration Release --output ${{ github.workspace }}/published


      - name: Create a zip file of the published app
        run: Compress-Archive -Path ${{ github.workspace }}/published/* -DestinationPath ${{ github.workspace }}/ASP-app.zip

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: ${{ github.workspace }}/ASP-app.zip
          retention-days: 1

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Extract artifact
        run: |
          Expand-Archive -Path ${{ github.workspace }}/ASP-app.zip -DestinationPath ${{ github.workspace }}/published

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'texasPost'
          slot-name: 'Production'
          package: '${{ github.workspace }}/published'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A3B84C7D48A541069A7C101689A39FF2 }}
