name: Build and deploy ASP app to Azure Web App - texasPost

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Install .NET SDK (if necessary)
        run: |
          choco install dotnet-sdk --version 7.0.100

      - name: Restore NuGet packages
        run: nuget restore backend/PostOfficeDB.csproj

      - name: Publish to folder
        run: msbuild backend/PostOfficeDB.sln /nologo /verbosity:m /t:Publish /p:PublishDir="${{ github.workspace }}/published"

      - name: List all folders and files
        run: Get-ChildItem -Path . -Recurse
        shell: pwsh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: '${{ github.workspace }}/published'
          retention-days: 1

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app
          path: '${{ github.workspace }}/published'  # Specify where to download the artifact

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'texasPost'
          slot-name: 'Production'
          package: '${{ github.workspace }}/published'  # Use the downloaded path
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A3B84C7D48A541069A7C101689A39FF2 }}
