name: Build and deploy ASP app to Azure Web App - texasPost

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup MSBuild path
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      # Install the .NET SDK if it's needed for building the project
      - name: Install .NET SDK (if necessary)
        run: |
          choco install dotnet-sdk --version 7.0.100  # Adjust this if you're using a different .NET version

      # Restore NuGet packages (ensure path is correct to your csproj or sln file)
      - name: Restore NuGet packages
        run: nuget restore backend/PostOfficeDB.csproj  # Adjust path if necessary

      # Build and publish the project
      - name: Publish to folder
        run: msbuild backend/PostOfficeDB.sln /nologo /verbosity:m /t:Build /p:Configuration=Release /p:OutDir=${{ github.workspace }}\published

      # List all folders and files to debug path issues using PowerShell syntax
      - name: List all folders and files
        run: Get-ChildItem -Path . -Recurse
        shell: pwsh

      # List contents of the published folder
      - name: List published folder contents
        run: Get-ChildItem -Path published -Recurse
        shell: pwsh

      # Upload the build artifact for the deploy job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: 'published/**'

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'texasPost'
          slot-name: 'Production'
          package: 'published'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A3B84C7D48A541069A7C101689A39FF2 }}
