name: Build and deploy ASP app to Azure Web App - texasPost

on:
  push:
    branches:
      - main  # Triggers when there is a push to the main branch
  workflow_dispatch:  # Allows you to manually trigger the workflow

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore NuGet packages
        run: dotnet restore backend/PostOfficeDB.csproj

      - name: Publish to folder
        run: dotnet publish backend/PostOfficeDB.csproj --configuration Release --output ${{ github.workspace }}/published

      - name: List all folders and files
        run: Get-ChildItem -Path . -Recurse
        shell: pwsh

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: ASP-app
          path: '${{ github.workspace }}/published'
          retention-days: 1

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: ASP-app

      - name: Extract artifact
        run: |
          Expand-Archive -Path ${{ github.workspace }}/ASP-app.zip -DestinationPath ${{ github.workspace }}/published

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'texasPost'
          slot-name: 'Production'
          package: '${{ github.workspace }}/published'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A3B84C7D48A541069A7C101689A39FF2 }}
